rvm:
  - 1.9.3
  - 2.0.0
  - 2.1
  - 2.2
  - ruby-head
  - rbx-2

os:
  - linux
  - osx

gemfile:
  - Gemfile

script: bundle exec rake test

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: rbx-2
